name: Helm Charts CI

on:
  push:
    branches:
      - '**'

jobs:
  helm-lint-and-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Lint Helm Chart
        run: helm lint ./myapp

      - name: CVE Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'kedjah07/myapp:latest'

      - name: Checkov Scan (IaC Security)
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
